#!/usr/bin/env python3
import rclpy
from rclpy.node import Node
from sensor_msgs.msg import Image
from cv_bridge import CvBridge
import cv2
from rclpy.qos import qos_profile_sensor_data

class ImageProcessor(Node):
    def __init__(self):
        super().__init__('show_image_node')
        self.bridge = CvBridge()
        
        # Lắng nghe camera với bộ lọc sóng chuẩn của ROS 2
        self.subscription = self.create_subscription(
            Image,
            '/image_raw',
            self.image_callback,
            qos_profile_sensor_data)
        self.get_logger().info("Đã khởi động Camera AI Node! Đang chờ ảnh...")

    def image_callback(self, msg):
        try:
            # Phiên dịch ảnh từ ROS sang định dạng OpenCV
            cv_image = self.bridge.imgmsg_to_cv2(msg, "bgr8")
            
            # --- KHU VỰC XỬ LÝ ẢNH ---
            # Vẽ vòng tròn đỏ và ghi chữ
            cv2.circle(cv_image, (150, 150), 50, (0, 0, 255), 3)
            cv2.putText(cv_image, "Ready for Flappy Bird!", (50, 50), cv2.FONT_HERSHEY_SIMPLEX, 1, (0, 255, 0), 2)
            # -------------------------
            
            # Hiển thị lên màn hình
            cv2.imshow("Camera View - ROS 2", cv_image)
            cv2.waitKey(1)
            
        except Exception as e:
            self.get_logger().error(f"Lỗi: {e}")

def main(args=None):
    rclpy.init(args=args)
    image_processor = ImageProcessor()
    
    try:
        rclpy.spin(image_processor)
    except KeyboardInterrupt:
        pass
    finally:
        image_processor.destroy_node()
        rclpy.shutdown()
        cv2.destroyAllWindows()

if _name_ == '_main_':
    main()